### PR TITLE
Refactoring 

### PR DESCRIPTION
**Pull request by geekskick**
Split the classes across different source files to increase maintainability.
Put the dimensions and colours into their own classes to modularise code.
Used the command pattern in the App class to allow the commands eg 'set_text' to be modified and added to at will. 
Added FindCairo.cmake so that it would build on macOS.
Added info lines to CMakeLists.txt for ease in build.
Put all cairo access into the wrapped cairo class (`wcairo`) so it's all in one place.

### CODE REVIEW

**Comment by zserge** [comment]
Thank you, I like the general idea of making it more modular, I also like the command pattern applied to the UI command dispatching.

I have a few concerns about the coding style though, as it's now too inconsistent. There is `.clang-format` file in the root of the repo, so if you run `clang-format` on all of the changed files you will get the right style automatically.

Also it's rather common (Google style, LLVM style) to make all type with a capital first letter (e.g. `Dimensions` and `Colour`) and I'd prefer to keep it that way. I also have doubts about `colour_t.h`, I'd probably use `colour.h` with a type of of `Colour`. I'm not sure whether it's common to use `.hpp` suffix, but as a C programmer it helps me to guess whether a header/library is plain C or C++. I don't insist, as I don't really know the good practices here.

It's not recommended to use underscore prefix for class fields (because it's a reserved identifier as per the standard - https://stackoverflow.com/questions/1421694/what-is-a-good-naming-convention-for-fields-and-accessors-in-c). Google style uses trailing underscore (e.g. `width_`), some use `m` prefix (e.g. `mWidth` or `m_width`). I'm ok with any of these as long as it consistent.

It also looks like in most cases the classes are outside of the `slide` namespace. Is it intentional? I also don't get the `Page_b` and `Document_b` naming. What does `_b` stand for? (Google recommends naming pure virtual classes as `PageInterface` and `DocumentInterface`, I also can imagine a java-like style of `IPage` and `IDocument`, but I haven't seen any other common notations really).

Then, it looks like the tests a now broken (`MockPage` class should be updated I believe).

Finally, when you replaced the fields to get an underscore prefix I believe you have accidentally modified the license file and a few others. Please, check the diff and maybe revert that.

This may sound like a lot of remarks, so if you have no time fixing those - I'm ok doing that by my own. And thanks for a generally useful pull request!

**Comment by geekskick** [comment]
Thanks for the comments, I’ll set to work getting those addressed - I didn’t know about the google style guides at all, at work we use snake_case and almost everything is an _t suffix, but I appreciate that I changed some stuff and not others so I’ll make sure it’s all the same. The same with _b is an abstract/virtrual class, I’ll change them to be in line with the Interface suffix. On my machine MockPage is building fine, but I’ll investigate on the CI link you have. 

Sorry that it’s been quite sloppy! I’ll fix it as per your comments.

**Comment by geekskick** [comment]
Google style guide used throughout, source files now have .cc suffix, headers all have .h suffix. All items are in slide namespace, and the MockPage should work. Still not implemented the write to PDF but that's for another pull request I think.

**Comment by zserge** [comment]
@geekskick Thanks a lot, it looks now much, much better to me! May I ask you to have a look at a few more things (not really important, just to make it closer to perfection):

* README.md seems to have `_bg.png` instead of `bg.png` in the URL (due to the global replace of class field with underscore, still not reverted back). Doesn't affect anything, but looks weird.
* There are some snake_case getters in the App class. I suspect those are not needed at all, but if you think they may be of use - please rename them to be consistent with other methods.
* Dimensions class may probably have width and height fields marked as `const`. This probably eliminates the reference getters (unless there is a reason for them that I missed).
* `encoding.cc` probably can be called `base64.cc` unless there is potential need for some other encodings?
* `WCairo` took me a while to realize it's a `CairoWrapper`, `CairoUtils` or maybe just `Cairo`.

Ok, then I would be 100% happy to merge it! Sorry for being that pedantic.

**Comment by geekskick** [comment]
It's not pedantic - it's your project and you're right to make sure that I'm contributing in the way you want 👍. 

* Regarding app accessors - the google style guide states that accessors may be in snake case the same as the variable names, e.g `m_my_thing` becomes `my_thing(void)`. I will change them to match but I thought I'd explain my reasoning.

* Dimensions I have left non const because in `SetPreviewSize::Execute` this is changed, so I have used the reference to do that rather than having a tedious `set_width()` `get_width()` etc. chaining the class itself to `const` would also, I think, make it less cohesive. I believe they should be marked `const` for their specific uses, e.g. in the case of `Page::size_.

* encoding: make sense! 

* WCairo: makes sense.

**Comment by zserge** [comment]
Now it's all perfect. Thanks for all your hard work!

**Comment by zserge** [comment]
@geekskick A quick question about cmake. After moving from `pkg_check_modules(Cairo cairo)` to `FindCairo.cmake` I now have a broken CI build. In fact, attempts to use MXE cross-compiler locally fail too. The reason is that `pkg_check_modules` ended up with a bigger list of transitive Cairo dependencies, including `libpng`, `pixman` etc. `FindCairo.cmake` on the other hand leaves only a full path to `cairo.a` library dropping the rest. Also, from what I can tell `FindCairo.cmake` doesn't differ that much from an excplicit `pkg-check_modules` call (yes, in handles version detection which we don't need anyway).

So, my question is - were there any build issues that we had to migrate from `pkg_check_modules` call to `FindCairo.cmake`? And if so, do you see any nice way to restore the functionality of MXE cross-builds and CI?

**Comment by geekskick** [comment]
I found that pkg_check_modules wasn’t able to find zlib even though it’s on my system:

```   
cmake ..
Package 'zlib', required by 'libpng', not found
```

```
brew install zlib
Warning: zlib 1.2.11 is already installed
```


I changed to FindCairo.cmake because I couldn’t get this working - most people got results with `xcode-select —install` but this yielded no results for me.

**Pull request merged**
